package com.ues.model;
// Generated 13-jun-2015 20:08:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Recursos generated by hbm2java
 */
public class Recursos  implements java.io.Serializable {


     private BigDecimal idRecursos;
     private TipoUsuario tipoUsuario;
     private String url;
     private Set<Menu> menus = new HashSet<Menu>(0);

    public Recursos() {
    }

	
    public Recursos(BigDecimal idRecursos, String url) {
        this.idRecursos = idRecursos;
        this.url = url;
    }
    public Recursos(BigDecimal idRecursos, TipoUsuario tipoUsuario, String url, Set<Menu> menus) {
       this.idRecursos = idRecursos;
       this.tipoUsuario = tipoUsuario;
       this.url = url;
       this.menus = menus;
    }
   
    public BigDecimal getIdRecursos() {
        return this.idRecursos;
    }
    
    public void setIdRecursos(BigDecimal idRecursos) {
        this.idRecursos = idRecursos;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set<Menu> getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set<Menu> menus) {
        this.menus = menus;
    }




}


