package com.ues.model;
// Generated 13-jun-2015 20:08:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoMenu generated by hbm2java
 */
public class TipoMenu  implements java.io.Serializable {


     private int idTipoMenu;
     private String nombre;
     private Set<Menu> menus = new HashSet<Menu>(0);

    public TipoMenu() {
    }

	
    public TipoMenu(int idTipoMenu, String nombre) {
        this.idTipoMenu = idTipoMenu;
        this.nombre = nombre;
    }
    public TipoMenu(int idTipoMenu, String nombre, Set<Menu> menus) {
       this.idTipoMenu = idTipoMenu;
       this.nombre = nombre;
       this.menus = menus;
    }
   
    public int getIdTipoMenu() {
        return this.idTipoMenu;
    }
    
    public void setIdTipoMenu(int idTipoMenu) {
        this.idTipoMenu = idTipoMenu;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Menu> getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set<Menu> menus) {
        this.menus = menus;
    }




}


