package com.ues.model;
// Generated 13-jun-2015 20:08:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private TipoUsuario tipoUsuario;
     private Persona persona;
     private String nombreUsuario;
     private String contrasena;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, TipoUsuario tipoUsuario, String nombreUsuario, String contrasena, Date fechaCreacion) {
        this.idUsuario = idUsuario;
        this.tipoUsuario = tipoUsuario;
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.fechaCreacion = fechaCreacion;
    }
    public Usuario(int idUsuario, TipoUsuario tipoUsuario, Persona persona, String nombreUsuario, String contrasena, Date fechaCreacion, Date fechaModificacion) {
       this.idUsuario = idUsuario;
       this.tipoUsuario = tipoUsuario;
       this.persona = persona;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


